-- 코드를 입력하세요
SELECT
    (CASE WHEN PRICE < 10000 THEN 0
    ELSE TRUNCATE(PRICE, -4) -- 1만원 미만이면 0, 그 이상은 만원 단위로 묶기
    END) AS PRICE_GROUP,
    COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP;